spring:
  cloud:
    vault:
      enabled: false
    config:
      enabled: false
    discovery:
      enabled: false
    loadbalancer:
      enabled: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      connect-timeout: 1s
      timeout: 1s
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

# Disable Eureka for Cloud Run
eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false

# Disable Zipkin
spring.zipkin:
  enabled: false

management:
  tracing:
    enabled: false
  health:
    redis:
      enabled: false
    mail:
      enabled: false
    kafka:
      enabled: false
    diskspace:
      enabled: false

logging:
  level:
    root: WARN
    com.udea.bancodigital: INFO

server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-stacktrace: never
